#### Thanya Mysore Santhosh                                                                                          
###### mysoresanthosh.th@northeastern.edu

#### Question 2- Write a function that creates an array with shape (n, m) that is all zeros except for the border (i.e., the first and last rows and columns), which should be filled with ones.

In [1]:
import numpy as np

In [2]:
def array(n,m): #defining a array() function with n and m as parameters. n and m denotes the shape of the array.
    a= np.zeros((n,m), dtype=int) #creates array filled with zeros
    a[0,:]=1 #accessing the first row and initializing all the elements in the first row as 1.
    a[-1,:]=1 #accessing the last row and initializing all the elements in the last row as 1.
    a[:,0]=1 #accessing the first column and initializing all the elements in the column row as 1.
    a[:,-1]=1 #accessing the last column and initializing all the elements in the last column as 1.
    return a

#### Output

##### Case 1 - when n<m

In [3]:
array(5,10) #call array() function by passing 5 and 10 as arguments

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

##### Case 2 - when n>m

In [4]:
array(9,4) #call array() function by passing 9 and 4 as arguments

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

##### Case 3 - when n=m

In [5]:
array(6,6) #call array() function by passing 6 and 6 as arguments

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])