#### Thanya Mysore Santhosh                                                                                          
###### mysoresanthosh.th@northeastern.edu

#### Question 1- Create a 10 × 10 array with random integers in the range 1-100 and print the following:

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 101, size=(10,10)) #creates a 10 x 10 array by generating random integers from 1 to 100.
print(arr)

[[66  5 33 73 21 32 98 94 24 33]
 [ 7 25 22 39 32 19 20 25 99 48]
 [24 55 83 61  8 36 42 13 95 58]
 [24 90 50 97 54 58 65 32 49 73]
 [76 26 65 77 99 16 96 81 57 36]
 [81 99 60 24 58 71 47 20 77 15]
 [48 15 70  1 67 97 94 99 72 84]
 [71 61 15 34 13 76 21  6 87 46]
 [29 19 30 41 22 82 76 75 94 78]
 [65 55 14 10 31 10 76 79 18 57]]


#### (a) The minimum and maximum values in the array.

In [3]:
minimum_value= arr.min() #computes minimum value in the array by using min() function
print("Minimum value:", minimum_value)

Minimum value: 1


In [4]:
maximum_value= arr.max() #computes maximum value in the array by using max() function.
print("Maximum value:", maximum_value)

Maximum value: 99


#### (b) The average value of every even row (rows 0, 2, ..., 8).

In [5]:
even_rows = arr[::2] #selecting every even rows 0,2,4,6,8
print("Every even row:\n", even_rows) #Displays every even row in the array
avg_of_even_row = np.mean(even_rows, axis=1) #using mean() function to calculate the average value of every even row
print("Average of every even row: ", avg_of_even_row)

Every even row:
 [[66  5 33 73 21 32 98 94 24 33]
 [24 55 83 61  8 36 42 13 95 58]
 [76 26 65 77 99 16 96 81 57 36]
 [48 15 70  1 67 97 94 99 72 84]
 [29 19 30 41 22 82 76 75 94 78]]
Average of every even row:  [47.9 47.5 62.9 64.7 54.6]


#### (c) The standard deviation in every odd column (columns 1, 3, ..., 9)

In [6]:
odd_col = arr[: , 1::2] #selecting every odd columns 1,3,5,7,9
print("Every odd column:\n" ,odd_col) #displays every odd column in the array
std_dev = np.std(odd_col, axis=0) #using std() function to calculate the standard deviation in every odd column
print("Standard deviation of every odd column:",std_dev)

Every odd column:
 [[ 5 73 32 94 33]
 [25 39 19 25 48]
 [55 61 36 13 58]
 [90 97 58 32 73]
 [26 77 16 81 36]
 [99 24 71 20 15]
 [15  1 97 99 84]
 [61 34 76  6 46]
 [19 41 82 75 78]
 [55 10 10 79 57]]
Standard deviation of every odd column: [30.5515957  29.22002738 29.41105234 34.43893146 20.57571384]


#### (d) How many rows contain a number less than 5?

In [7]:
rows= np.any(arr<5, axis=1) #using any() function to access rows that contain a number less than 5
row_count= np.sum(rows) #using sum() function to calculate the sum of total rows that contain a number less than 5
print("Total number of rows that contain a number less than 5: " ,row_count)

Total number of rows that contain a number less than 5:  1


#### (e) Which columns contain a number greater than 90? (print the indexes of the columns)

In [8]:
cols= np.any(arr>90, axis=0) #using any() function to access columns that contain a number greater than 90
indices= np.where(cols) #using sum() function to access the indexes of the columns that contain a number greater than 90
print("Indices of the column that contain a number greater than 90: ",indices)

Indices of the column that contain a number greater than 90:  (array([1, 3, 4, 5, 6, 7, 8], dtype=int64),)


#### (f) Which numbers appear in the matrix more than twice?

In [9]:
flattened_array= arr.flatten() # using flatten() function to flatten a  multidimensional array into one dimension
unique_values, count = np.unique(flattened_array, return_counts = True) # using unique() function to find the unique values in the array and count the occurrence of each unique number in the array.
result = unique_values[count>2] #finding a number that appears more than twice
print("Numbers that appear more than twice in the matrix:" ,result)

Numbers that appear more than twice in the matrix: [15 24 32 58 65 76 94 99]


#### (g) How many rows contain duplicate values?

In [10]:
def check_duplicates(row): #defining a function to check whether any row contains duplicate values
    return len(row) != len(np.unique(row)) #using len() function to access and compare the length of the total number of elements in the row with the length of unique elements in the row
count_duplicates_in_row= np.sum([check_duplicates(row) for row in arr]) #check for duplicate values in the row by accessing each row in the array using for() loop and use sum() function to count duplicate values in a row
print("Number of rows that contain duplicate values: ",count_duplicates_in_row)

Number of rows that contain duplicate values:  3
