#### Thanya Mysore Santhosh                                                                                          
###### mysoresanthosh.th@northeastern.edu

#### Question 7- Given the following matrix A and vector b:

In [1]:
import numpy as np

##### a) Compute the determinant of matrix A

In [2]:
A = np.array([
          [4,2,1],
          [3,1,5],
          [2,1,3]
])
determinant = np.linalg.det(A) #linalg is linear algebra module which includes det() function. This computes the determinant of the matrix
print("Determinant of matrix A:", determinant)

Determinant of matrix A: -5.000000000000001


In [3]:
b= np.array([10, 6, 7])

##### (b) Check if matrix A is invertible. If it is, find its inverse

In [4]:
if determinant != 0:
    print("Matrix is invertible")
    inverse = np.linalg.inv(A) #use inv() function to compute the inverse of the matrix
    print("Inverse:\n" ,inverse)
else:
    print("Matrix is not invertible")

Matrix is invertible
Inverse:
 [[ 0.4  1.  -1.8]
 [-0.2 -2.   3.4]
 [-0.2  0.   0.4]]


##### c) Solve the linear system Ax = b for x.

In [5]:
x = np.linalg.solve(A, b) #use solve() function to compute the solution of the linear matrix equation Ax = b
print("Solution:" ,x)

Solution: [-2.6  9.8  0.8]


##### (d) Compute the eigenvalues and eigenvectors of A.

In [6]:
eigen_vals, eigen_vecs = np.linalg.eig(A) #use eig() function to compute the eigenvalues and eigenvectors of the matrix A
print("Eigen values:", eigen_vals)
print("Eigen vectors:\n",eigen_vecs)

Eigen values: [ 7.04804585  1.44343285 -0.4914787 ]
Eigen vectors:
 [[ 0.58800699  0.65315053  0.40044041]
 [ 0.66832949 -0.61183564 -0.91573217]
 [ 0.45561329 -0.44615192  0.03289476]]


##### e) Verify that the eigenvectors satisfy the equation Av = λv for each eigenvalue λ and eigenvector v.

In [7]:
Av= A @ eigen_vecs #Av
lambdav= eigen_vals*eigen_vecs #λv
print("Av:\n", Av)
print("λv:\n", lambdav)
if np.allclose(Av, lambdav): # use allclose() function to compare two arrays element-wise and to check if they are "close" to each other.
    print("The equation Av = λv is satisfied for each eigenvalue λ and eigenvector v")
else:
    print("The equation Av = λv is not satisfied for each eigenvalue λ and eigenvector v")

Av:
 [[ 4.14430024  0.94277893 -0.19680793]
 [ 4.7104169  -0.88314365  0.45006286]
 [ 3.21118334 -0.64399034 -0.01616707]]
λv:
 [[ 4.14430024  0.94277893 -0.19680793]
 [ 4.7104169  -0.88314365  0.45006286]
 [ 3.21118334 -0.64399034 -0.01616707]]
The equation Av = λv is satisfied for each eigenvalue λ and eigenvector v
