#### Thanya Mysore Santhosh                                                                                          
###### mysoresanthosh.th@northeastern.edu

#### Question 8- In this exercise, you will build a simple grid-based game where a player moves on a 10 × 10 grid, and the goal is to reach a randomly placed target. The player can move in four directions (up, down, left, right), and the game ends when the player reaches the target.

In [1]:
import numpy as np

##### a) Initialize a 10 × 10 grid as a NumPy array filled with zeros, where:

###### • The player’s starting position is represented by a 1.

###### • The target is randomly placed and represented by a 9.

###### • Randomly place obstacles on 15% of the grid that the player cannot move through, represented by −1

In [2]:
grid_dim = 10 #defines the dimension of the grid (i.e. 10x10 matrix)
grid = np.zeros((grid_dim, grid_dim), dtype=int) #creates an empty grid (10x10) initialised with zeros

start_position = (np.random.randint(0, grid_dim), np.random.randint(0, grid_dim)) #provides the player with random position to start. generates a random integer from 0 to 9 for both row and column
grid[start_position] = 1 #the value at the random position chosen for the player to start is set to 1

while True: #while loop is used to ensure that the target is placed in a position different from the player's start position
    target_position = (np.random.randint(0, grid_dim), np.random.randint(0, grid_dim)) #provides a random position for the target to be placed. generates a random integer from 0 to 9 for both row and column
    if target_position != start_position: #part where it checks whether the target is placed in a position different from the player's start position.
        grid[target_position] = 9 #the value at the random position chosen to place the target is set to 9
        break

obstacles = int(0.15 * grid_dim * grid_dim) #as given, obstacles should be placed on 15% of the grid 
existing_obstacles = 0 #variable to count the number of already placed obstacles
while existing_obstacles < obstacles: #if the already placed obstacle is less than the obstacles yet to be placed, then we can generate a new obstacle position and place an obstacle there.
    obstacle_position = (np.random.randint(0, grid_dim), np.random.randint(0, grid_dim)) #provides a random position for the obstacle to be placed. generates a random integer from 0 to 9 for both row and column
    if grid[obstacle_position] == 0: #before placing an obstacle, check whether the chosen random position is empty (to avoid placing it on player's start and target position)
        grid[obstacle_position] = -1 #as mentioned above, the obstacle is set to -1
        existing_obstacles += 1 #the count of already placed obstacles is incremented by 1

print("Randomly generated 10x10 grid:\n",grid)

Randomly generated 10x10 grid:
 [[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]


##### (b) The player can input movement commands (’w’ for up, ’s’ for down, ’a’ for left, ’d’ for right) to move on the grid.

In [3]:
def movement_commands(com, start_position): #define a movement_commands() function to move on the grid. Parameters are com and start_position. com is a command provided to the player to move in a particular direction
    x, y = start_position #we know that, the player's start position on the grid is stored as a tuple(x, y). unpack the existing values in that tuple and store them in x and y variables respectively.
    
    if com == 'w' and x > 0:  #checks if the command is "w" and the player is not at the top row
        return (x - 1, y) #move the player up by decreasing the x-coordinate by 1
    
    elif com == 's' and x < grid_dim - 1:  #checks if the command is "s" and the player is not at the last row
        return (x + 1, y) #move the player down by increasing the x-coordinate by 1
    
    elif com == 'a' and y > 0:  #checks if the command is "a" and the player is not at the first column
        return (x, y - 1) #move the player left by decreasing the y-coordinate by 1
    
    elif com == 'd' and y < grid_dim - 1:  #checks if the command is "d" and the player is not at the last column
        return (x, y + 1) #move the player right by increasing the y-coordinate by 1
    
    return start_position  # If the command passed is invalid, return the same position

##### (c) The grid should update after each move. If the player moves out of bounds, the move is ignored.

In [4]:
def updated_grid(grid, previous_position, new_position): #use updated_grid() function to update the grid after each move
    grid[previous_position] = 0  #the old player's position is set to 0
    grid[new_position] = 1  #the new player's position is updated with 1

##### (d) The game ends when the player reaches the target.

In [5]:
def check_target(start_position, target_position): #using check_target() function to check whether the player has reached the target position.
    return start_position == target_position #firstly, it checks whether the player's current position is equal to the player's target position. If they are equal, it indicates that the player has reached the target position. 

##### (e) Implement a scoring system that decreases with each move, and display the score when the game ends.

In [6]:
starting_score = 100 #implementing a scoring system by setting the starting score of the game to 100
score = starting_score # initialise the current score with the starting score of the game

#### Main loop

In [7]:
score = starting_score #set the starting score
start_game = True #determines the game state

while start_game: #use while() loop to keep the game running until the player reaches the target position
    print("\nCurrent Grid:")
    print(grid)
    print(f"Score: {score}")
    
    com = input("Enter your move (w = up, s = down, a = left, d = right): ").lower() #use input() function for the user to input the movement commands and convert them into lowercase
    new_player_position = movement_commands(com, start_position) #update the new player position based on the command input provided
    
    if grid[new_player_position] == -1: #before updating the grid, check if the new player position contains an obstacle
        print("You hit an obstacle! Try again.")
        continue  #skips the rest of the code inside the loop and proceeds to the next iteration
    
    updated_grid(grid, start_position, new_player_position) #call updated_grid() function to update the grid with new player position
    start_position = new_player_position #initialise the current player position with the new player position
    
    score -= 1 #subtract 1 from score for each move
    
    if check_target(start_position, target_position): #call check_target() function to check if the player's current position is same as the target's position
        start_game = False #set start_game as "False" indicating that the game ended
        print("\nPlayer has reached the target position!")
        print(f"Final Score: {score}")
        break


Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 100


Enter your move (w = up, s = down, a = left, d = right):  W



Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  1  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 99


Enter your move (w = up, s = down, a = left, d = right):  W



Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 98


Enter your move (w = up, s = down, a = left, d = right):  A



Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  0  0  1  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 97


Enter your move (w = up, s = down, a = left, d = right):  a



Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  0  1  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 96


Enter your move (w = up, s = down, a = left, d = right):  a



Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  0  1  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 95


Enter your move (w = up, s = down, a = left, d = right):  a



Current Grid:
[[ 0  0  0 -1  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0  0 -1]
 [ 0  0  9  1  0  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0 -1]
 [ 0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0]
 [ 0  0  0  0  0  0 -1 -1  0  0]]
Score: 94


Enter your move (w = up, s = down, a = left, d = right):  a



Player has reached the target position!
Final Score: 93
